### ISSUE TITLE
may you share info about similar softwaer

### ISSUE THREAD

**Issue by Sandy4321** [AnestisTouloumis/SimCorMultRes#2]
Great package, thank you, may you share links to similar software to compare performance of your package with other packages
Even if another software is written in another computer language
Thanks a lot in advance

**Comment by AnestisTouloumis** [comment]
For R packages, please see the references in the accompanying journal article available at https://journal.r-project.org/archive/2016/RJ-2016-034/.
I am afraid that I cannot help with software written in another language.

**Comment by Sandy4321** [comment]
thanks for soon answer, but what is about anther packages in R
it is possible there are another attempts to solve this problem, 
may you share pls

**Comment by Sandy4321** [comment]
from given link we see

CRAN packages:  GenOrd, MultiOrd, mvtBinaryEP, 
may you help understand are there other R packages for simulation data and what is the main difference of your package, please
